### PR TITLE
drivedb.h: Samsung Portable SSD T7

### PR DESCRIPTION
**Pull request by gertvdijk**
Related ticket: https://www.smartmontools.org/ticket/1403

`-x -q noserial` on this device (with change to drivedb.h):

```
smartctl 7.3 2021-06-26 r5227 [x86_64-linux-5.4.0-77-generic] (CircleCI)
Copyright (C) 2002-21, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Number:                       Samsung Portable SSD T7
Firmware Version:                   FXG42P2Q
PCI Vendor/Subsystem ID:            0x144d
IEEE OUI Identifier:                0x002538
Total NVM Capacity:                 500,107,862,016 [500 GB]
Unallocated NVM Capacity:           0
Controller ID:                      5
NVMe Version:                       1.3
Number of Namespaces:               1
Namespace 1 Size/Capacity:          500,107,862,016 [500 GB]
Namespace 1 Utilization:            67,162,112 [67.1 MB]
Namespace 1 Formatted LBA Size:     512
Local Time is:                      Thu Jul 22 17:03:13 2021 CEST
Firmware Updates (0x16):            3 Slots, no Reset required
Optional Admin Commands (0x0007):   Security Format Frmw_DL
Optional NVM Commands (0x001f):     Comp Wr_Unc DS_Mngmt Wr_Zero Sav/Sel_Feat
Log Page Attributes (0x03):         S/H_per_NS Cmd_Eff_Lg
Maximum Data Transfer Size:         512 Pages
Warning  Comp. Temp. Threshold:     49 Celsius
Critical Comp. Temp. Threshold:     53 Celsius

Supported Power States
St Op     Max   Active     Idle   RL RT WL WT  Ent_Lat  Ex_Lat
 0 +     4.83W       -        -    0  0  0  0        0       0
 1 +     3.54W       -        -    1  1  1  1        0       0
 2 +     3.04W       -        -    2  2  2  2        0       0
 3 -   0.0500W       -        -    3  3  3  3    26000    1000

Supported LBA Sizes (NSID 0x1)
Id Fmt  Data  Metadt  Rel_Perf
 0 +     512       0         0

=== START OF SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

SMART/Health Information (NVMe Log 0x02)
Critical Warning:                   0x00
Temperature:                        29 Celsius
Available Spare:                    100%
Available Spare Threshold:          10%
Percentage Used:                    0%
Data Units Read:                    17 [8.70 MB]
Data Units Written:                 0
Host Read Commands:                 337
Host Write Commands:                0
Controller Busy Time:               0
Power Cycles:                       8
Power On Hours:                     1
Unsafe Shutdowns:                   7
Media and Data Integrity Errors:    0
Error Information Log Entries:      0
Warning  Comp. Temperature Time:    0
Critical Comp. Temperature Time:    0
Temperature Sensor 1:               29 Celsius
Temperature Sensor 2:               28 Celsius

Warning: NVMe Get Log truncated to 0x200 bytes, 0x200 bytes zero filled
Error Information (NVMe Log 0x01, 16 of 64 entries)
No Errors Logged
```

### CODE REVIEW

**Comment by chrfranke** [comment]
Thanks. If possible, please provide a sample `smartctl [-q noserial] -x ...` output for this device.

**Comment by gertvdijk** [comment]
@chrfranke done; edited the initial message above.
(will also do that in my other PR)

**Comment by adggit** [comment]
I vote for a merge of @gertvdijk's commit (e630312d66f445737d05047d988a1baea95282ac) for this pull-request.

I can confirm that my output of `-x -q noserial` is essentially identical to that posted by @gertvdijk in this thread for my Samsung Portable SSD T7 (which has ASMedia ASM2362 USB/NVMe passthrough). In particular, I have the same warning line:
`Warning: NVMe Get Log truncated to 0x200 bytes, 0x200 bytes zero filled`

**Comment by parkerlreed** [comment]
Same output on latest svn/git
```
smartctl 7.3 2022-01-16 r5304M [x86_64-linux-5.16.1-arch1-1] (local build)
Copyright (C) 2002-22, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Number:                       Samsung Portable SSD T7
Firmware Version:                   FXG42P2Q
PCI Vendor/Subsystem ID:            0x144d
IEEE OUI Identifier:                0x002538
Total NVM Capacity:                 2,000,398,934,016 [2.00 TB]
Unallocated NVM Capacity:           0
Controller ID:                      5
NVMe Version:                       1.3
Number of Namespaces:               1
Namespace 1 Size/Capacity:          2,000,398,934,016 [2.00 TB]
Namespace 1 Utilization:            555,625,525,248 [555 GB]
Namespace 1 Formatted LBA Size:     512
Local Time is:                      Fri Jan 21 15:36:28 2022 EST
Firmware Updates (0x16):            3 Slots, no Reset required
Optional Admin Commands (0x0007):   Security Format Frmw_DL
Optional NVM Commands (0x001f):     Comp Wr_Unc DS_Mngmt Wr_Zero Sav/Sel_Feat
Log Page Attributes (0x03):         S/H_per_NS Cmd_Eff_Lg
Maximum Data Transfer Size:         512 Pages
Warning  Comp. Temp. Threshold:     54 Celsius
Critical Comp. Temp. Threshold:     56 Celsius

Supported Power States
St Op     Max   Active     Idle   RL RT WL WT  Ent_Lat  Ex_Lat
 0 +     4.83W       -        -    0  0  0  0        0       0
 1 +     3.54W       -        -    1  1  1  1        0       0
 2 +     3.04W       -        -    2  2  2  2        0       0
 3 -   0.0500W       -        -    3  3  3  3    26000    1000

Supported LBA Sizes (NSID 0x1)
Id Fmt  Data  Metadt  Rel_Perf
 0 +     512       0         0

=== START OF SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

SMART/Health Information (NVMe Log 0x02)
Critical Warning:                   0x00
Temperature:                        27 Celsius
Available Spare:                    100%
Available Spare Threshold:          10%
Percentage Used:                    0%
Data Units Read:                    1,166,553 [597 GB]
Data Units Written:                 1,258,870 [644 GB]
Host Read Commands:                 8,321,154
Host Write Commands:                9,318,811
Controller Busy Time:               35
Power Cycles:                       42
Power On Hours:                     6
Unsafe Shutdowns:                   35
Media and Data Integrity Errors:    0
Error Information Log Entries:      0
Warning  Comp. Temperature Time:    0
Critical Comp. Temperature Time:    0
Temperature Sensor 1:               27 Celsius
Temperature Sensor 2:               28 Celsius

Warning: NVMe Get Log truncated to 0x200 bytes, 0x200 bytes zero filled
Error Information (NVMe Log 0x01, 16 of 64 entries)
No Errors Logged
```

**Comment by chrfranke** [comment]
Added in [r5385](https://www.smartmontools.org/changeset/5385) (c0af9d3), [r5388](https://www.smartmontools.org/changeset/5388)

**Pull request closed without merging**
