### PR TITLE
Fix runtime problems on big-engian OpenBSD platforms.

### PR DESCRIPTION
**Pull request by dusxmt**
Greetings, I've just switched to OpenBSD on one of my older laptops, and I've noticed that smartctl wasn't working for some reason.

I was able to track down the issue to being with the cylinder specification in the ATA ioctl() calls, they were passed in little-endian format, though it seems that they're supposed to be passed in the host byte ordering, a similar change was made to the NetBSD port 15 years ago: https://github.com/smartmontools/smartmontools/commit/be63f968f1cfdce761dff9198a1ce997aec97194

Here are the logs of smartctl with and without this fix:
[without-fix.log](https://github.com/smartmontools/smartmontools/files/4730832/without-fix.log)
[with-fix.log](https://github.com/smartmontools/smartmontools/files/4730830/with-fix.log)

### CODE REVIEW

**Comment by samm-git** [comment]
Thank you for your patch. Just a side note - OpenBSD code using old interface and is not compatible with many new smartmontools possibilities (see https://www.smartmontools.org/ticket/102 for the reference). Would be great if you can do such port. If not - i can make this patch, but will require some testing, as i currently do not have any OpenBSD systems around.

**Comment by samm-git** [comment]
P.S. code for the netbsd, just for the reference:

https://www.smartmontools.org/changeset/4343

**Comment by samm-git** [comment]
@dusxmt could you please try patch from this PR? https://github.com/samm-git/smartmontools/pull/1/files

I did it without real hardware, so unable to test.

**Comment by samm-git** [comment]
Patch in this PR updated  (sorry, its get messed with one in my fork)

**Comment by dusxmt** [comment]
Doing a 'smartctl -a' works, but I've noticed that if I try to run a short self-test, it does start the test, but also reports an error message, I'll try to look into what's causing it:
[smartctl-query.log](https://github.com/smartmontools/smartmontools/files/4734667/smartctl-query.log)
[smartctl-short-test.log](https://github.com/smartmontools/smartmontools/files/4734668/smartctl-short-test.log)

**Comment by samm-git** [comment]
btw, found why my usb is not working - https://github.com/openbsd/src/blob/master/sys/scsi/scsi_ioctl.c

they are whitelisting SCSI commands "safe to send" and SAT is not here. It could be possible to workaround using SAT12 code they have, but not sure if i want to spend time on it.

**Comment by samm-git** [comment]
ok, it does not make a sense anyway. I would suggest to report this to the upstream, without removing this "safe" filter it is not possible to check smart status in anything non-SAT12 compatible (e.g. jmicron, etc)

**Comment by samm-git** [comment]
@dusxmt please try with increased timeout, if i am not wrong 0x01 code is timeout error.

**Comment by dusxmt** [comment]
That did indeed fix it, and it makes sense, it takes 3.3 seconds for the call to complete with this old drive, whereas the timeout was set to 1 second before.  (and I know, this drive probably won't live for too long now, with those relocated sectors, but I have a replacement on the way (44-pin IDE to SD card))
```
=== START OF OFFLINE IMMEDIATE AND SELF-TEST SECTION ===
Sending command: "Execute SMART Short self-test routine immediately in off-line mode".

REPORT-IOCTL: Device=/dev/wd0c Command=SMART IMMEDIATE OFFLINE InputParameter=1
 Input:   FR=0xd4, SC=...., LL=0x01, LM=0x4f, LH=0xc2, DEV=...., CMD=0xb0
 [Duration: 3.339s]
 Output: ERR=0x00, SC=0x00, LL=0x01, LM=0x4f, LH=0xc2, DEV=0xa0, STS=0xb0
REPORT-IOCTL: Device=/dev/wd0c Command=SMART IMMEDIATE OFFLINE returned 0
Drive command "Execute SMART Short self-test routine immediately in off-line mode" successful.
Testing has begun.
Please wait 2 minutes for test to complete.
Test will complete after Fri Jun  5 10:17:48 2020 CEST
Use smartctl -X to abort test.
```

**Comment by dusxmt** [comment]
Will send an email to OpenBSD about the whitelisted SCSI commands.

**Comment by samm-git** [comment]
@dusxmt actually i am now not 100% sure that this is due to it. Anyway, would be great if someone can test it to see where is a problem. If done i can try to implement USB->SCSI device mapping in smartctl, so it will recognize such devices automatically

**Comment by samm-git** [comment]
@dusxmt ok, may be it is just fault of that specific device, i think you can ignore it. Tried with another one and now able to see everything with `-d sat`. I will see if i can do usb autodetection, thank you for the testing )

**Comment by dusxmt** [comment]
No problems :)  Will still send a mail to the mailing lists, so that hopefully people with various different setups can test out these patches, since I only have this one drive (tried attaching an external USB drive, but the laptop probably wasn't able to provide enough power, it kept on starting and shutting down)

**Comment by samm-git** [comment]
Ok, going to merge it now. JFYI - i found no way to match device name with usb id (or at least connected umass driver). Only available api is `SCIOCIDENTIFY` , but it is returning only type (integer), bus, target and lun. I did not found any API to query system to see what is on this specific  bus/target/lun. If you will fine a way to do it - we can implement USB autodetection as well.

**Comment by samm-git** [comment]
Fixed in r5063. Thank you for initial patch and testing!

**Pull request closed without merging**
