### PR TITLE
Add NVMe short and long self-tests to smartd

### LINKED ISSUE #218: With a033019 smartd does not run scheduled tests on NVME devices (ATAs are fine)
The relevant `smartd.conf`: 

```
DEVICESCAN -a -l xerror -l offlinests -m root@localhost -M test -n standby,10,q -s (O/../.././(00|06|12|18)|S/../.././01|L/../../6/03)
```

The Linux system has `sda`, `sdb`, `sdc` and `nvme0`.

`sda - sdc` look like this:

```
smartctl pre-7.5 (build date Oct 16 2023) [x86_64-linux-6.5.9-200.fc38.x86_64] (local build)
Copyright (C) 2002-23, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Family:     Samsung based SSDs
Device Model:     Samsung SSD 870 EVO 1TB
...

SMART Extended Self-test Log Version: 1 (1 sectors)
Num  Test_Description    Status                  Remaining  LifeTime(hours)  LBA_of_first_error
# 1  Short offline       Completed without error       00%      3248         -
# 2  Extended offline    Completed without error       00%      3228         -
# 3  Short offline       Completed without error       00%      3224         -
# 4  Short offline       Completed without error       00%      3200         -
# 5  Short offline       Completed without error       00%      3176         -
# 6  Short offline       Completed without error       00%      3152         -
# 7  Short offline       Completed without error       00%      3128         -
# 8  Short offline       Completed without error       00%      3104         -
# 9  Short offline       Completed without error       00%      3080         -
#10  Extended offline    Completed without error       00%      3060         -
#11  Short offline       Completed without error       00%      3056         -
#12  Short offline       Completed without error       00%      3032         -
#13  Short offline       Completed without error       00%      3008         -
#14  Short offline       Completed without error       00%      2984         -
#15  Short offline       Completed without error       00%      2960         -
#16  Short offline       Completed without error       00%      2936         -
#17  Short offline       Completed without error       00%      2912         -
#18  Extended offline    Completed without error       00%      2892         -
#19  Short offline       Completed without error       00%      2888         -
```

But for `nvme0` the situation is different:

```
smartctl pre-7.5 (build date Oct 16 2023) [x86_64-linux-6.5.9-200.fc38.x86_64] (local build)
Copyright (C) 2002-23, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Number:                       Samsung SSD 970 EVO 250GB

...

Error Information (NVMe Log 0x01, 16 of 64 entries)
Num   ErrCount  SQId   CmdId  Status  PELoc          LBA  NSID    VS  Message
  0        190     0  0x000c  0x4004      -            0     0     -  Invalid Field in Command

Self-test Log (NVMe Log 0x06)
Self-test status: No self-test in progress
Num  Test_Description  Status                       Power_on_Hours  Failing_LBA  NSID Seg SCT Code
 0   Short             Completed: failed segments             1617     65075488     1   7   -    -
``` 

The failing short was launched manually via `smartctl -t short /dev/nvme0`

As you can see from history no regularly scheduled tests are performed on NVME on the same system where they are successfully performed on eligible ATA devices.

### PR DESCRIPTION
**Pull request by arcivanov**
fixes #218, ticket 1649

### CODE REVIEW

**Comment by arcivanov** [comment]
Some of the test examples:

Offline Immediate:

```
smartd pre-7.5 (build date Nov  5 2023) [x86_64-linux-6.5.7-200.fc38.x86_64] (local build)
Copyright (C) 2002-23, Bruce Allen, Christian Franke, www.smartmontools.org

Opened configuration file /etc/smartmontools/smartd.conf
Configuration file /etc/smartmontools/smartd.conf was parsed, found DEVICESCAN, scanning devices
Device: /dev/nvme0, opened
Device: /dev/nvme0, Samsung SSD 990 PRO 4TB, S/N:S7KGNJ0W907543M, FW:0B2QJXG7, 4.00 TB
Device: /dev/nvme0, is SMART capable. Adding to "monitor" list.
Monitoring 0 ATA/SATA, 0 SCSI/SAS and 1 NVMe devices
Executing test of <mail> to root@localhost ...
Test of <mail> to root@localhost: successful
Device: /dev/nvme0, opened NVMe device
^C
Signal INT - rereading configuration file /etc/smartmontools/smartd.conf (CONTROL-\ quits)

Opened configuration file /etc/smartmontools/smartd.conf
Configuration file /etc/smartmontools/smartd.conf was parsed, found DEVICESCAN, scanning devices
Device: /dev/nvme0, opened
Device: /dev/nvme0, Samsung SSD 990 PRO 4TB, S/N:S7KGNJ0W907543M, FW:0B2QJXG7, 4.00 TB
Device: /dev/nvme0, is SMART capable. Adding to "monitor" list.
Monitoring 0 ATA/SATA, 0 SCSI/SAS and 1 NVMe devices
Executing test of <mail> to root@localhost ...
Test of <mail> to root@localhost: successful
Device: /dev/nvme0, opened NVMe device
Device: /dev/nvme0, NSID: 0xffffffff, not capable of Offline Immediate Test
^C
Signal INT - rereading configuration file /etc/smartmontools/smartd.conf (CONTROL-\ quits)

```

Short:
```
Opened configuration file /etc/smartmontools/smartd.conf
Configuration file /etc/smartmontools/smartd.conf was parsed, found DEVICESCAN, scanning devices
Device: /dev/nvme0, opened
Device: /dev/nvme0, Samsung SSD 990 PRO 4TB, S/N:123456790123456, FW:0B2QJXG7, 4.00 TB
Device: /dev/nvme0, is SMART capable. Adding to "monitor" list.
Monitoring 0 ATA/SATA, 0 SCSI/SAS and 1 NVMe devices
Executing test of <mail> to root@localhost ...
Test of <mail> to root@localhost: successful
Device: /dev/nvme0, opened NVMe device
Device: /dev/nvme0, NSID: 0xffffffff, starting scheduled Short Self-Test.
^C
Signal INT - rereading configuration file /etc/smartmontools/smartd.conf (CONTROL-\ quits)

Opened configuration file /etc/smartmontools/smartd.conf
Configuration file /etc/smartmontools/smartd.conf was parsed, found DEVICESCAN, scanning devices
Device: /dev/nvme0, opened
Device: /dev/nvme0, Samsung SSD 990 PRO 4TB, S/N:123456790123456, FW:0B2QJXG7, 4.00 TB
Device: /dev/nvme0, is SMART capable. Adding to "monitor" list.
Monitoring 0 ATA/SATA, 0 SCSI/SAS and 1 NVMe devices
Executing test of <mail> to root@localhost ...
Test of <mail> to root@localhost: successful
Device: /dev/nvme0, opened NVMe device
Device: /dev/nvme0, NSID: 0xffffffff, skip scheduled Short Self-Test; 1% remaining of current Self-Test.
^C
Signal INT - rereading configuration file /etc/smartmontools/smartd.conf (CONTROL-\ quits)

Opened configuration file /etc/smartmontools/smartd.conf
Configuration file /etc/smartmontools/smartd.conf was parsed, found DEVICESCAN, scanning devices
Device: /dev/nvme0, opened
Device: /dev/nvme0, Samsung SSD 990 PRO 4TB, S/N:123456790123456, FW:0B2QJXG7, 4.00 TB
Device: /dev/nvme0, is SMART capable. Adding to "monitor" list.
Monitoring 0 ATA/SATA, 0 SCSI/SAS and 1 NVMe devices
Executing test of <mail> to root@localhost ...
Test of <mail> to root@localhost: successful
Device: /dev/nvme0, opened NVMe device
Device: /dev/nvme0, NSID: 0xffffffff, skip scheduled Short Self-Test; 4% remaining of current Self-Test.
^C
Signal INT - rereading configuration file /etc/smartmontools/smartd.conf (CONTROL-\ quits)

Opened configuration file /etc/smartmontools/smartd.conf
Configuration file /etc/smartmontools/smartd.conf was parsed, found DEVICESCAN, scanning devices
Device: /dev/nvme0, opened
Device: /dev/nvme0, Samsung SSD 990 PRO 4TB, S/N:123456790123456, FW:0B2QJXG7, 4.00 TB
Device: /dev/nvme0, is SMART capable. Adding to "monitor" list.
Monitoring 0 ATA/SATA, 0 SCSI/SAS and 1 NVMe devices
Executing test of <mail> to root@localhost ...
Test of <mail> to root@localhost: successful
Device: /dev/nvme0, opened NVMe device
Device: /dev/nvme0, NSID: 0xffffffff, skip scheduled Short Self-Test; 4% remaining of current Self-Test.
^C
Signal INT - rereading configuration file /etc/smartmontools/smartd.conf (CONTROL-\ quits)

Opened configuration file /etc/smartmontools/smartd.conf
Configuration file /etc/smartmontools/smartd.conf was parsed, found DEVICESCAN, scanning devices
Device: /dev/nvme0, opened
Device: /dev/nvme0, Samsung SSD 990 PRO 4TB, S/N:123456790123456, FW:0B2QJXG7, 4.00 TB
Device: /dev/nvme0, is SMART capable. Adding to "monitor" list.
Monitoring 0 ATA/SATA, 0 SCSI/SAS and 1 NVMe devices
Executing test of <mail> to root@localhost ...
Test of <mail> to root@localhost: successful
Device: /dev/nvme0, opened NVMe device
Device: /dev/nvme0, NSID: 0xffffffff, skip scheduled Short Self-Test; 6% remaining of current Self-Test.
^\smartd received signal 3: Quit
smartd is exiting (exit status 0)
[root@ai-karellen-lap smartmontools]# nano /etc/smartmontools/smartd.conf 
[root@ai-karellen-lap smartmontools]# smartd -d
smartd pre-7.5 (build date Nov  5 2023) [x86_64-linux-6.5.7-200.fc38.x86_64] (local build)
Copyright (C) 2002-23, Bruce Allen, Christian Franke, www.smartmontools.org

Opened configuration file /etc/smartmontools/smartd.conf
Configuration file /etc/smartmontools/smartd.conf was parsed, found DEVICESCAN, scanning devices
Device: /dev/nvme0, opened
Device: /dev/nvme0, Samsung SSD 990 PRO 4TB, S/N:123456790123456, FW:0B2QJXG7, 4.00 TB
Device: /dev/nvme0, is SMART capable. Adding to "monitor" list.
Monitoring 0 ATA/SATA, 0 SCSI/SAS and 1 NVMe devices
Executing test of <mail> to root@localhost ...
Test of <mail> to root@localhost: successful
Device: /dev/nvme0, opened NVMe device
^C
Signal INT - rereading configuration file /etc/smartmontools/smartd.conf (CONTROL-\ quits)

Opened configuration file /etc/smartmontools/smartd.conf
Configuration file /etc/smartmontools/smartd.conf was parsed, found DEVICESCAN, scanning devices
Device: /dev/nvme0, opened
Device: /dev/nvme0, Samsung SSD 990 PRO 4TB, S/N:123456790123456, FW:0B2QJXG7, 4.00 TB
Device: /dev/nvme0, is SMART capable. Adding to "monitor" list.
Monitoring 0 ATA/SATA, 0 SCSI/SAS and 1 NVMe devices
Executing test of <mail> to root@localhost ...
Test of <mail> to root@localhost: successful
Device: /dev/nvme0, opened NVMe device
Device: /dev/nvme0, NSID: 0xffffffff, skip scheduled Long Self-Test; 42% remaining of current Self-Test.
^C
```

Long:
```
Opened configuration file /etc/smartmontools/smartd.conf
Configuration file /etc/smartmontools/smartd.conf was parsed, found DEVICESCAN, scanning devices
Device: /dev/nvme0, opened
Device: /dev/nvme0, Samsung SSD 990 PRO 4TB, S/N:S7KGNJ0W907543M, FW:0B2QJXG7, 4.00 TB
Device: /dev/nvme0, is SMART capable. Adding to "monitor" list.
Monitoring 0 ATA/SATA, 0 SCSI/SAS and 1 NVMe devices
Executing test of <mail> to root@localhost ...
Test of <mail> to root@localhost: successful
Device: /dev/nvme0, opened NVMe device
Device: /dev/nvme0, NSID: 0xffffffff, skip scheduled Long Self-Test; 98% remaining of current Self-Test.
^C
Signal INT - rereading configuration file /etc/smartmontools/smartd.conf (CONTROL-\ quits)

Opened configuration file /etc/smartmontools/smartd.conf
Configuration file /etc/smartmontools/smartd.conf was parsed, found DEVICESCAN, scanning devices
Device: /dev/nvme0, opened
Device: /dev/nvme0, Samsung SSD 990 PRO 4TB, S/N:S7KGNJ0W907543M, FW:0B2QJXG7, 4.00 TB
Device: /dev/nvme0, is SMART capable. Adding to "monitor" list.
Monitoring 0 ATA/SATA, 0 SCSI/SAS and 1 NVMe devices
Executing test of <mail> to root@localhost ...
Test of <mail> to root@localhost: successful
Device: /dev/nvme0, opened NVMe device
Device: /dev/nvme0, NSID: 0xffffffff, starting scheduled Long Self-Test.
^C
Signal INT - rereading configuration file /etc/smartmontools/smartd.conf (CONTROL-\ quits)

Opened configuration file /etc/smartmontools/smartd.conf
Configuration file /etc/smartmontools/smartd.conf was parsed, found DEVICESCAN, scanning devices
Device: /dev/nvme0, opened
Device: /dev/nvme0, Samsung SSD 990 PRO 4TB, S/N:S7KGNJ0W907543M, FW:0B2QJXG7, 4.00 TB
Device: /dev/nvme0, is SMART capable. Adding to "monitor" list.
Monitoring 0 ATA/SATA, 0 SCSI/SAS and 1 NVMe devices
Executing test of <mail> to root@localhost ...
Test of <mail> to root@localhost: successful
Device: /dev/nvme0, opened NVMe device
Device: /dev/nvme0, NSID: 0xffffffff, skip scheduled Long Self-Test; 1% remaining of current Self-Test.
^C
```

**Comment by jumbi77** [comment]
Wow thanks, that is a long wanted feature. Looking forward to get this integrated. Much thanks.

Since you you may have further interest in extending smartd for nvme even more, the ticket [1190](https://www.smartmontools.org/ticket/1190) is a long wanted feature too.

**Comment by arcivanov** [comment]
> Wow thanks, that is a long wanted feature. Looking forward to get this integrated. Much thanks.
> 
> Since you you may have further interest in extending smartd for nvme even more, the ticket [1190](https://www.smartmontools.org/ticket/1190) is a long wanted feature too.

Let me see what's involved in this.

**Comment by arcivanov** [comment]
> Wow thanks, that is a long wanted feature. Looking forward to get this integrated. Much thanks.

FYI I'm running unofficial RPM builds for the head of of smartmontools: https://copr.fedorainfracloud.org/coprs/karellen/smartmontools-next/

**Comment by arcivanov** [comment]
> Wow thanks, that is a long wanted feature. Looking forward to get this integrated. Much thanks.
> 
> Since you you may have further interest in extending smartd for nvme even more, the ticket [1190](https://www.smartmontools.org/ticket/1190) is a long wanted feature too.

@jumbi77 please see #221

**Comment by chrfranke** [comment]
Thank for this PR.

Starting self-tests frequently (the easy part) is only useful if the self-test log is evaluated for new failed test later (the more difficult part). Otherwise `smartd` would not issue any warning or other information if a test failed. So please consider also the `-l selftest` directive and possibly `-l selfteststs` as mentioned in [ticket 1649](https://www.smartmontools.org/ticket/1649).

Some further notes:
```
+static int DoNVMeSelfTest(const dev_config & cfg, dev_state & state, nvme_device * device, char testtype)
```
Please use `lower_snake_case` for new functions.

```
+  // Read Identify Controller always
+  nvme_id_ctrl id_ctrl;
+  if (!nvme_read_id_ctrl(device, id_ctrl)) {
+    PrintOut(LOG_CRIT, "Device: %s, read NVMe Identify Controller failed: %s\n", name, device->get_errmsg());
+    return 1;
+  }
+
+  // Check for self-test support
+  bool self_test_sup = !!(id_ctrl.oacs & 0x0010);
+  unsigned self_test_nsid = device->get_nsid(); // TODO: Support NSID=0 to test controller
```
 Don't read identify controller always during each turn. Move the self-test support check to device registration function as done in all other cases. It will also be needed for `-l selftest` support.

```
+  // Check for capability to do the test
+  unsigned char smart_selftest_type = 0;
+  const char *testname = nullptr;
+  switch (testtype) {
+  case 'O':
+ ...
+    break;
+  }
```
The complexity of this large switch is not needed. Set `state.not_cap_short = state.not_cap_short = !self_test_sup;` during device registration and use `next_scheduled_test(cfg, state, true);` later

The final PR should also contain a patch for `ChangeLog` file. This GH project is only a R/O mirror of the upstream SVN repository at sourceforge (the smartmontools project is older than GH and even git).

**Comment by arcivanov** [comment]
> Starting self-tests frequently (the easy part) is only useful if the self-test log is evaluated for new failed test later (the more difficult part). Otherwise `smartd` would not issue any warning or other information if a test failed. So please consider also the `-l selftest` directive and possibly `-l selfteststs` as mentioned in [ticket 1649](https://www.smartmontools.org/ticket/1649).

Will do!

> 
> Some further notes:
> 
> ```
> +static int DoNVMeSelfTest(const dev_config & cfg, dev_state & state, nvme_device * device, char testtype)
> ```

I simply followed the pattern for ATA and SCSI. Because both ATA and SCSI followed the same naming convention it was easy to figure out what was going on. Are you *sure* you want me to make the new function look not like the ATA and SCSI ones?

> 
> ```
> +  // Read Identify Controller always
> +  nvme_id_ctrl id_ctrl;
> +  if (!nvme_read_id_ctrl(device, id_ctrl)) {
> +    PrintOut(LOG_CRIT, "Device: %s, read NVMe Identify Controller failed: %s\n", name, device->get_errmsg());
> +    return 1;
> +  }
> +
> +  // Check for self-test support
> +  bool self_test_sup = !!(id_ctrl.oacs & 0x0010);
> +  unsigned self_test_nsid = device->get_nsid(); // TODO: Support NSID=0 to test controller
> ```
> 
> Don't read identify controller always during each turn. Move the self-test support check to device registration function as done in all other cases. It will also be needed for `-l selftest` support.

Will do.

> 
> ```
> +  // Check for capability to do the test
> +  unsigned char smart_selftest_type = 0;
> +  const char *testname = nullptr;
> +  switch (testtype) {
> +  case 'O':
> + ...
> +    break;
> +  }
> ```
> 
> The complexity of this large switch is not needed. Set `state.not_cap_short = state.not_cap_short = !self_test_sup;` during device registration and use `next_scheduled_test(cfg, state, true);` later

Will do.

> 
> The final PR should also contain a patch for `ChangeLog` file. This GH project is only a R/O mirror of the upstream SVN repository at sourceforge (the smartmontools project is older than GH and even git).

OK.

**Comment by chrfranke** [comment]
84aa5be is unrelated to the topic of this PR, in particular in does not implement `-l selftest` which is mandatory for self-test support.

Please avoid ugly C macros to generate code.  If such variability is really needed here, try to use template functions instead.

**Comment by arcivanov** [comment]
> [84aa5be](https://github.com/smartmontools/smartmontools/commit/84aa5bec629945f679ab583f63b67fa055f992d7) is unrelated to the topic of this PR

It literally fixes the issues you've outlined in https://github.com/smartmontools/smartmontools/pull/219#issuecomment-1795044187

At any rate, I'm adding features into this PR and then we'll split them into several if you think it's necessary.

**Comment by arcivanov** [comment]
```
Device: /dev/nvme0, opened
Device: /dev/nvme0, Samsung SSD 970 EVO 250GB, S/N:123456789012345, FW:2B2QEXE7, 250 GB
Device: /dev/nvme0, is SMART capable. Adding to "monitor" list.
Device: /dev/nvme0, state read from /var/lib/smartmontools/Samsung_SSD_970_EVO_250GB-123456789012345.nvme.state
...
Device: /dev/nvme0, opened NVMe device
Device: /dev/nvme0, NVMe Prefailure Attribute: Media Errors changed from 0 to 1
Sending warning via <mail> to root@localhost ...
Warning via <mail> to root@localhost: successful
Device: /dev/nvme0, previous self-test Completed without error
Device: /dev/nvme0, Self-Test Log error count increased from 0 to 1
Sending warning via <mail> to root@localhost ...
Warning via <mail> to root@localhost: successful
Device: /dev/nvme0, Short Self-Test has failed: Completed: failed segments; POH 1617 hrs, Segment 7, NSID 0x1, LBA 65075488, Status Code Type 0x0, Status Code 0x0
...
Device: /dev/nvme0, state written to /var/lib/smartmontools/Samsung_SSD_970_EVO_250GB-123456789012345.nvme.state
```

**Comment by arcivanov** [comment]
```
# cat /var/lib/smartmontools/Samsung_SSD_970_EVO_250GB-123456789012345.nvme.state
# smartd state file
scheduled-test-next-check = 1699237096
mail.2.count = 1
mail.2.first-sent-time = 1699865712
mail.2.last-sent-time = 1699865712
mail.3.count = 1
mail.3.first-sent-time = 1699865712
mail.3.last-sent-time = 1699865712
nvme-err-log-entries = 191
nvme-media-errors = 1
nvme-self-test-errors = 1
nvme-self-test-last-error-test-op = 1
nvme-self-test-last-error-test-res = 7
nvme-self-test-last-error-poh = 1617
nvme-self-test-last-error-nsid = 1
nvme-self-test-last-error-lba = 65075488
```

**Comment by arcivanov** [comment]
For the same drive the `smartctl -x /dev/nvme0` provides:

```
Error Information (NVMe Log 0x01, 16 of 64 entries)
Num   ErrCount  SQId   CmdId  Status  PELoc          LBA  NSID    VS  Message
  0        191     0  0x0010  0x4004      -            0     0     -  Invalid Field in Command

Self-test Log (NVMe Log 0x06)
Self-test status: No self-test in progress
Num  Test_Description  Status                       Power_on_Hours  Failing_LBA  NSID Seg SCT Code
 0   Extended          Completed without error                1617            -     -   -   -    -
 1   Short             Completed: failed segments             1617     65075488     1   7   -    -

```

**Comment by arcivanov** [comment]
@chrfranke I left the "ugly macros" in as comments for comparison. If you still want them gone and like lambdas better I'll remove them.
I left the `DoNVMeSelfTest` name in place for consistency. If you still want it renamed to new style, I'll do it.

**Comment by chrfranke** [comment]
Using lambdas instead of templates is an interesting approach. Will take some time to decide. A quick look shows that teh `get_state_value` function is not needed because the value can simply be passed.

For future PRs, please don't do later off-topic additions (here: _attributes monitoring_ on top of _self test_) to keep the PR reasonable small for faster review.

Did you test everything by inserting temporary code which emulates device behavior which really triggers the warnings?

**Comment by arcivanov** [comment]
@chrfranke 
Templates won't work here, as there is operator and other subtle variability - i.e. it could be done on the preprocessor level but not with the templates without lambdas, i.e. the template is pointless. I'll clean up the get part.

As far as testing I actually used an NVMe drive that is the reason for this PR - both media error and failed segment short test are fully natural and I was testing on that drive (along with a normal one on another machine). 
I.e. the feature in this PR encapsulates what I encountered in the wild and ultimately need to test. See https://github.com/smartmontools/smartmontools/pull/219#issuecomment-1807739874

Meanwhile, I need to ask your advice regarding mail messaging - seems to me that between these two lines:

https://github.com/smartmontools/smartmontools/pull/219/files#diff-f900cc9fb3cd2f4d60a0425be22fb8e07012b1e3ec135763044f06f845c8753dR4153

https://github.com/smartmontools/smartmontools/pull/219/files#diff-f900cc9fb3cd2f4d60a0425be22fb8e07012b1e3ec135763044f06f845c8753dR4177

the second never sends the email, because of the "one email per type in unit time per mailing policy" feature. I still want both messages to go out. Should I concatenate the two into a single email or is there another standardized mechanism you would want me to use for this?

**Comment by arcivanov** [comment]
Considering that `-l selftest` part is following ATA self-test behavior almost verbatim it's a surprising finding, to say the least. Since there are no ordinal-based attributes for NVMe like there are for SMART, and dealing with the pointer arithmetic is worse, and you didn't want macros, the field-name-based solution was presented.

Frankly, the entire tool could be rewritten in Python from the ground up "in the next weeks", foregoing all the complexity and expressive verbosity of the C++. :smile:

**Comment by arcivanov** [comment]
It's been 11 weeks. Any progress in implementing an alternative solution?

**Comment by chrfranke** [comment]
> It's been 11 weeks. Any progress in implementing an alternative solution?

Sorry no. I'm preparing a possible move of the smartmontools project from sourceforge to github. Any non-trivial enhancements have lower priority until then.

**Comment by arcivanov** [comment]
Thanks for the update. Would it make more sense to adopt this solution as is (if it is functionally satisfactory) and then work on a better alternative as time permits?

**Comment by jumbi77** [comment]
> > It's been 11 weeks. Any progress in implementing an alternative solution?
> 
> Sorry no. I'm preparing a possible move of the smartmontools project from sourceforge to github. Any non-trivial enhancements have lower priority until then.

Do you may can give an update when to revisit this PR ? I am really looking forward to get this (#219) and also #221 upstreamed to smartmontools.

**Comment by chrfranke** [comment]
Self NVMe test support for smartd will likely be included in smartmontools 7.5 which will be released later this year.

**Comment by jumbi77** [comment]
> NVMe self-test support for smartd will likely be included in smartmontools 7.5 which will be released later this year.

@chrfranke Can I may ask you about the progress ? [Project 7.5](https://www.smartmontools.org/milestone/Release%207.5) only have 5 tickets open, do you plan to integrate NVMe test support yourself or can/should we may ask @arcivanov to rebase this work for 7.5? In any case much thanks to both of you!

**Comment by chrfranke** [comment]
Work is in progress based on the self-test related part of this PR. The off-topic parts will be considered later.

**Comment by chrfranke** [comment]
NVMe self-test support was added in [r5633](https://www.smartmontools.org/changeset/5633) (2af89a2).

I didn't use this PR, sorry. I prefer a simplified approach which re-uses the existing count/hours heuristics to detect new failed self-tests. This avoids the complexity needed to store the last failed log entry.

**Comment by arcivanov** [comment]
That's fine, as long as there is self-test functionality with failure detection I don't care.

**Pull request closed without merging**
