### PR TITLE
Virtium LLC - Merge DriveDB.h changes into master.

### PR DESCRIPTION
**Pull request by johnnynguyen541**
Creating Pull request to merge changes for Virtium products into main branch.

### CODE REVIEW

**Comment by chrfranke** [comment]
Thanks for the patch. Issues:

- **TESTING IS MANDATORY**. The regexp look good but the entries contain syntax errors:
```
$ smartctl -B drivedb-pull73.h -P showall
...
MODEL FAMILY:       StorFly SATA 6Gbps pSLC SSD
...
                    172 Total_Blk_Erase_Failures
          Error: Attribute name too long ------^
...
Found 11 syntax error(s) in database.
```

- Avoid trailing spaces.

- -v options with are already supported by the DEFAULT entry should be present but commented-out (see also other SSD entries). For example:
```
  { "DEFAULT",
   ...
    "-v 12,raw48,Power_Cycle_Count "

  {
    "StorFly TuffDrive eUSB",
   ...
  //"-v 12,raw48,Power_Cycle_Count "
```

- Merge entries with similar attributes: `StorFly SATA 6Gbps pSLC SSD` and `StorFly SATA 6Gbps TLC SSD`. There is no need to mention NAND types in the attribute names.

- Merge entries with mutual exclusive attribute differences: all firmware variants of `StorFly SATA 6Gbps SSDs` could be combined into one entry.

- Provide at least one `smartctl -x ...` sample output for each remaining entry. This is mandatory to qualify an entry for inclusion. See also our [FAQ](https://www.smartmontools.org/wiki/FAQ#MyATASATAdriveisnotinthesmartctlsmartddatabase).

Note that we may modify entries later to unify attribute naming or include other drive series which have similar attribute sets.

**Comment by johnnynguyen541** [comment]
Updated with those corrections.

Attached smartctl -x ... output:

[smartctl-StorFly-VSFBM8CC120G-160.txt](https://github.com/smartmontools/smartmontools/files/5711185/smartctl-StorFly-VSFBM8CC120G-160.txt)

**Comment by chrfranke** [comment]
Are you sure that the `smartctl -x` output was produced with a database file with 0ab1df9 applied ?
```
$ smartctl -B drivedb-pull73-0ab1df9.h -P showall 'StorFly VSFBM8CC120G-160'
drivedb-pull73-0ab1df9.h(715): Missing regular expression for drive model

$ sed -n 712,715p drivedb-pull73-0ab1df9.h
  {
    "StorFly SATA 6Gbps SSDs",
    // tested with Virtium StorFly VSFBM8CC120G-160
    "", <=== Missing regular expression for drive model
```

**Comment by johnnynguyen541** [comment]
Hi Christian, it should be the correct database file from `0ab1df9 `applied ?

**Comment by chrfranke** [comment]
The current diff of this PR (0ab1df9 to 309eac4 inclusive) shows that there is no regular expression left to match drive model string:
```
+  {
+    "StorFly SATA 6Gbps SSDs",
+    // tested with Virtium StorFly VSFBM8CC120G-160
+    "",
+    // C - commercial, I industrial
+    "0202-000", "",
+   ...
+    "-v 249,raw48,Spare_Blocks_Remaining "
+  },
```
This is a syntax error as reported by `smartctl ... -P showall ...` command. Matching solely on firmware string is not acceptable.

**Comment by chrfranke** [comment]
This PR is broken, see the [full diff](73.diff) and the [patch series](73.patch).

**Pull request closed without merging**
