### PR TITLE
Extend WMI timeout

### PR DESCRIPTION
**Pull request by EatonZ**
I recently ran into a problem with a user where they were getting an "Unable to read USB device ID" error message. After digging into it with them, I discovered a problem with the way smartctl uses WMI.

The WMI query in this case was returning `WBEM_S_TIMEDOUT`, which is a [non-error](https://learn.microsoft.com/en-us/windows/win32/wmisdk/wmi-non-error-constants). I considered adding a check for this error so that it would not blow up the entire operation, but decided to instead raise the timeout. I chose the maximum value because that is what [Microsoft has for their default](https://learn.microsoft.com/en-us/dotnet/api/system.management.managementoptions.timeout#property-value).

This change resolves the issue for the user and should also help many other users as well.

### CODE REVIEW

**Comment by EatonZ** [comment]
@chrfranke In many years of using System.Management with the default (max) timeout, I have never seen it hang excessively. I think max should be fine.

**Comment by EatonZ** [comment]
Hi @chrfranke, what do you think? Let me know, and hopefully this can make it for 7.5. 🙂

**Comment by chrfranke** [comment]
How about extending the timeout to a much larger value, like 1 minute ?

**Comment by EatonZ** [comment]
@chrfranke Very well - done!

**Comment by chrfranke** [comment]
Thanks.

This repo is still a R/O mirror of the upstream SVN repo at SF. So please add a patch for the `ChangeLog` file to your PR.

**Comment by EatonZ** [comment]
Done!

**Comment by chrfranke** [comment]
Applied in [r5640](https://www.smartmontools.org/changeset/5640) (de0bd65), thanks!

**Pull request closed without merging**
