### PR TITLE
Update drivedb.h_MSD210

### PR DESCRIPTION
**Pull request by phison-someone**
To Whom It May Concern,
 
I am writing to submit a pull request to modify Phison's MSD210 series. 
Please let me know if you have any questions. Thank you.

### CODE REVIEW

**Comment by chrfranke** [comment]
Please provide an `smartctl -x -a ...` output of an affected device.

**Comment by phison-someone** [comment]
Script started on 2024-10-16 14:22:39+08:00 [TERM="xterm-256color" TTY="/dev/pts/0" COLUMNS="79" LINES="23"]
]0;root@nvme: ~/Desktop/20240909_YW/smartmontools-7.4[01;32mroot@nvme[00m:[01;34m~/Desktop/20240909_YW/smartmontools-7.4[00m# ls./configure.ac [7Pifconfigsmartctl --all /dev/sdc[11Pmake install[K./configure [Kure [8Pmake installsmartctl --all /dev/sdc[15Pifconfig./configure.ac [Kls[K[Ksmartctl -x -a /dev/sdc
smartctl 7.4 2023-08-01 r5530 [x86_64-linux-5.10.32-ryder-20211006] (local build)
Copyright (C) 2002-23, Bruce Allen, Christian Franke, www.smartmontools.org

=== START OF INFORMATION SECTION ===
Model Family:     Phison Driven OEM SSDs
Device Model:     MSD210-M8320GPSCB5UFI-S122
Serial Number:    C3E907481DA900129811
Firmware Version: SCFI75.0
User Capacity:    320,072,933,376 bytes [320 GB]
Sector Size:      512 bytes logical/physical
Rotation Rate:    Solid State Device
Form Factor:      M.2
TRIM Command:     Available, deterministic, zeroed
Device is:        In smartctl database
ATA Version is:   ACS-3 (minor revision not indicated)
SATA Version is:  SATA 3.1, 6.0 Gb/s (current: 6.0 Gb/s)
Local Time is:    Wed Oct 16 14:23:28 2024 CST
SMART support is: Available - device has SMART capability.
SMART support is: Enabled
AAM feature is:   Unavailable
APM level is:     254 (maximum performance)
Rd look-ahead is: Enabled
Write cache is:   Enabled
DSN feature is:   Unavailable
ATA Security is:  Disabled, NOT FROZEN [SEC1]
Wt Cache Reorder: Unavailable

=== START OF READ SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

General SMART Values:
Offline data collection status:  (0x00)	Offline data collection activity
					was never started.
					Auto Offline Data Collection: Disabled.
Self-test execution status:      (   0)	The previous self-test routine completed
					without error or no self-test has ever 
					been run.
Total time to complete Offline 
data collection: 		(   30) seconds.
Offline data collection
capabilities: 			 (0x79) SMART execute Offline immediate.
					No Auto Offline data collection support.
					Suspend Offline collection upon new
					command.
					Offline surface scan supported.
					Self-test supported.
					Conveyance Self-test supported.
					Selective Self-test supported.
SMART capabilities:            (0x0003)	Saves SMART data before entering
					power-saving mode.
					Supports SMART auto save timer.
Error logging capability:        (0x01)	Error logging supported.
					General Purpose Logging supported.
Short self-test routine 
recommended polling time: 	 (   1) minutes.
Extended self-test routine
recommended polling time: 	 (   2) minutes.
Conveyance self-test routine
recommended polling time: 	 (   3) minutes.

SMART Attributes Data Structure revision number: 16
Vendor Specific SMART Attributes with Thresholds:
ID# ATTRIBUTE_NAME          FLAGS    VALUE WORST THRESH FAIL RAW_VALUE
  1 Raw_Read_Error_Rate     PO-R--   100   100   050    -    0
  9 Power_On_Hours          -O--C-   100   100   000    -    75
 12 Power_Cycle_Count       -O--C-   100   100   000    -    15
168 SATA_Phy_Error_Count    -O--C-   100   100   000    -    0
170 Bad_Blk_Ct_Lat/Erl      PO----   100   100   010    -    0/290
173 Erase_Ct_Max/Avg        -O--C-   100   100   000    -    1/0
192 Unsafe_Shutdown_Count   -O--C-   100   100   000    -    12
194 Temperature_Celsius     PO---K   058   054   000    -    42 (Min/Max 27/46)
218 CRC_Error_Count         PO-R--   100   100   050    -    0
231 SSD_Life_Left           PO--C-   100   100   000    -    100
241 Lifetime_Writes_GiB     -O--C-   100   100   000    -    0
                            ||||||_ K auto-keep
                            |||||__ C event count
                            ||||___ R error rate
                            |||____ S speed/performance
                            ||_____ O updated online
                            |______ P prefailure warning

General Purpose Log Directory Version 1
SMART           Log Directory Version 1 [multi-sector log support]
Address    Access  R/W   Size  Description
0x00       GPL,SL  R/O      1  Log Directory
0x01           SL  R/O      1  Summary SMART error log
0x02           SL  R/O     51  Comprehensive SMART error log
0x03       GPL     R/O     64  Ext. Comprehensive SMART error log
0x04       GPL,SL  R/O      8  Device Statistics log
0x06           SL  R/O      1  SMART self-test log
0x07       GPL     R/O      1  Extended self-test log
0x09           SL  R/W      1  Selective self-test log
0x10       GPL     R/O      1  NCQ Command Error log
0x11       GPL     R/O      1  SATA Phy Event Counters log
0x30       GPL,SL  R/O      9  IDENTIFY DEVICE data log
0x80-0x9f  GPL,SL  R/W     16  Host vendor specific log
0xc1-0xcb  GPL     VS   32760  Device vendor specific log
0xdf       GPL     VS   32760  Device vendor specific log

SMART Extended Comprehensive Error Log Version: 1 (64 sectors)
No Errors Logged

SMART Error Log Version: 1
No Errors Logged

SMART Extended Self-test Log Version: 1 (1 sectors)
No self-tests have been logged.  [To run self-tests, use: smartctl -t]

SMART Self-test log structure revision number 1
No self-tests have been logged.  [To run self-tests, use: smartctl -t]

SMART Selective self-test log data structure revision number 1
 SPAN  MIN_LBA  MAX_LBA  CURRENT_TEST_STATUS
    1        0        0  Not_testing
    2        0        0  Not_testing
    3        0        0  Not_testing
    4        0        0  Not_testing
    5        0        0  Not_testing
Selective self-test flags (0x0):
  After scanning selected spans, do NOT read-scan remainder of disk.
If Selective self-test is pending on power-up, resume after 0 minute delay.

SCT Commands not supported

Device Statistics (GP Log 0x04)
Page  Offset Size        Value Flags Description
0x01  =====  =               =  ===  == General Statistics (rev 1) ==
0x01  0x008  4              15  ---  Lifetime Power-On Resets
0x01  0x010  4              75  ---  Power-on Hours
0x01  0x018  6          409809  ---  Logical Sectors Written
0x01  0x020  6            3350  ---  Number of Write Commands
0x01  0x028  6          221551  ---  Logical Sectors Read
0x01  0x030  6            2075  ---  Number of Read Commands
0x01  0x038  6       272081130  ---  Date and Time TimeStamp
0x04  =====  =               =  ===  == General Errors Statistics (rev 1) ==
0x04  0x008  4               0  ---  Number of Reported Uncorrectable Errors
0x04  0x010  4               0  ---  Resets Between Cmd Acceptance and Completion
0x05  =====  =               =  ===  == Temperature Statistics (rev 1) ==
0x05  0x008  1              42  ---  Current Temperature
0x05  0x010  1              41  ---  Average Short Term Temperature
0x05  0x018  1               -  ---  Average Long Term Temperature
0x05  0x020  1              46  ---  Highest Temperature
0x05  0x028  1              27  ---  Lowest Temperature
0x05  0x030  1              43  ---  Highest Average Short Term Temperature
0x05  0x038  1              41  ---  Lowest Average Short Term Temperature
0x05  0x040  1               -  ---  Highest Average Long Term Temperature
0x05  0x048  1               -  ---  Lowest Average Long Term Temperature
0x05  0x050  4               0  ---  Time in Over-Temperature
0x05  0x058  1              70  ---  Specified Maximum Operating Temperature
0x05  0x060  4               0  ---  Time in Under-Temperature
0x05  0x068  1               0  ---  Specified Minimum Operating Temperature
0x06  =====  =               =  ===  == Transport Statistics (rev 1) ==
0x06  0x008  4              23  ---  Number of Hardware Resets
0x06  0x018  4               0  ---  Number of Interface CRC Errors
0x07  =====  =               =  ===  == Solid State Device Statistics (rev 1) ==
0x07  0x008  1               0  ---  Percentage Used Endurance Indicator
                                |||_ C monitored condition met
                                ||__ D supports DSN
                                |___ N normalized value

Pending Defects log (GP Log 0x0c) not supported

SATA Phy Event Counters (GP Log 0x11)
ID      Size     Value  Description
0x0001  2            0  Command failed due to ICRC error
0x0003  2            0  R_ERR response for device-to-host data FIS
0x0004  2            0  R_ERR response for host-to-device data FIS
0x0006  2            0  R_ERR response for device-to-host non-data FIS
0x0007  2            0  R_ERR response for host-to-device non-data FIS
0x0008  2            0  Device-to-host non-data FIS retries
0x0009  4            4  Transition from drive PhyRdy to drive PhyNRdy
0x000a  4            3  Device-to-host register FISes sent due to a COMRESET
0x000f  2            0  R_ERR response for host-to-device data FIS, CRC
0x0010  2            0  R_ERR response for host-to-device data FIS, non-CRC
0x0012  2            0  R_ERR response for host-to-device non-data FIS, CRC
0x0013  2            0  R_ERR response for host-to-device non-data FIS, non-CRC

]0;root@nvme: ~/Desktop/20240909_YW/smartmontools-7.4[01;32mroot@nvme[00m:[01;34m~/Desktop/20240909_YW/smartmontools-7.4[00m# exit
exit

Script done on 2024-10-16 14:23:39+08:00 [COMMAND_EXIT_CODE="0"]

**Comment by chrfranke** [comment]
PLEASE don't paste console output unchanged to a comment. Use redirection+attachment or _Markdown syntax for preformatted text_. The "Preview" tab is your friend.

**Comment by phison-someone** [comment]
please refer to the attached log, thanks.

[logtest001.log](https://github.com/user-attachments/files/17391052/logtest001.log)

**Comment by chrfranke** [comment]
- The `Phison Driven OEM SSDs` is only intended for drives from strange device vendors which decide to provide only an unspecific ATA IDENTIFY string like `SATA SSD`. The entry additionally uses a firmware regex. Drives with a specific identity like ` MSD210-M8320GPSCB5UFI-S122` should be added to `Phison Driven SSDs` instead. 

- This change from the PR would affect also all other drives matched by the entry:
  ```diff
  -    "-v 173,raw16(avg16),MaxAvgErase_Ct "
  +    "-v 173,raw24/raw24:z10z32,Erase_Ct_Max/Avg "
  ```
  Do all Phison firmware versions use this assignment?
  If not, do all Phison firmware version matching `S[89ABCH]F[DMI][0-9T][0-9]\\.[0-9]` use this assignment?

- This repo is still a R/O mirror of the upstream SVN repo at SF. So please include a patch to the `ChangeLog` file in your PR. See recent PR #285 for an example.

**Comment by phison-someone** [comment]
Yes, all Phison firmware versions use this assignment.

I've tried to update chagelog but failed, did i upload to the wrong place?
Or should i create another PR to upload the ChangeLog?
Would you mind helping me with it? really appreciate.

**Comment by phison-someone** [comment]
Hi @chrfranke , 
Please see the changes: fd6cafaedae99a9d509f79226ebb78d25a7e7858

Thanks.

**Pull request closed without merging**
