### PR TITLE
Adding Seagate Ironwolf 110 and Nytro 1351/1551 drives

### PR DESCRIPTION
**Pull request by vonericsen**
These changes add Seagate's Ironwolf 110 SSD and Nytro 1351 & 1551 SSDs to the smartctl database.

### CODE REVIEW

**Comment by vonericsen** [comment]
I've looked at the CircleCI and it seems to have some sort of scripting issue. 
I don't see anything in the output indicating that this is a compile problem.

**Comment by samm-git** [comment]
@vonericsen feel free to ignore circle ci, PR integration is not yet completed (in my todo list)

**Comment by samm-git** [comment]
Please fix your pr by not including values already defined in the SSD base definition

**Comment by vonericsen** [comment]
@samm-git thanks for the information!
I have updated the attributes I want to commit.
Please let me know if there are other changes I need to make.

**Comment by samm-git** [comment]
Committed revision 4899, thank you!

**Pull request closed without merging**
